In [1]:
import torch

seq_len = 6
d_head = 6

Q = (torch.arange(seq_len * d_head).reshape(seq_len, d_head) + 1.)  / 10
K = (torch.arange(seq_len * d_head).reshape(seq_len, d_head) + 1.)  / 10
V = (torch.arange(seq_len * d_head).reshape(seq_len, d_head) + 1.)  / 10


In [2]:
Q

tensor([[0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000, 1.0000, 1.1000, 1.2000],
        [1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000],
        [1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000],
        [2.5000, 2.6000, 2.7000, 2.8000, 2.9000, 3.0000],
        [3.1000, 3.2000, 3.3000, 3.4000, 3.5000, 3.6000]])

In [3]:
torch.softmax(Q @ K.T, dim=1) @ V

tensor([[2.8643, 2.9643, 3.0643, 3.1643, 3.2643, 3.3643],
        [3.0797, 3.1797, 3.2797, 3.3797, 3.4797, 3.5797],
        [3.0977, 3.1977, 3.2977, 3.3977, 3.4977, 3.5977],
        [3.0997, 3.1997, 3.2997, 3.3997, 3.4997, 3.5997],
        [3.1000, 3.2000, 3.3000, 3.4000, 3.5000, 3.6000],
        [3.1000, 3.2000, 3.3000, 3.4000, 3.5000, 3.6000]])

In [4]:
torch.softmax(Q[0, :] @ K.T, dim=0)

tensor([0.0013, 0.0046, 0.0164, 0.0577, 0.2033, 0.7167])

# One-shot

In [5]:
seq_len = 4
d_head = 4

Q = (torch.arange(seq_len * d_head).reshape(seq_len, d_head) + 1.)  / 10
K = (torch.arange(seq_len * d_head).reshape(seq_len, d_head) + 1.)  / 10
V = (torch.arange(seq_len * d_head).reshape(seq_len, d_head) + 1.)  / 10
O = torch.zeros((seq_len, d_head))


m = torch.full((seq_len, 1), -torch.inf)
l = torch.zeros((seq_len, 1))

mi = m  # shape Br x 1
li = l  # shape Br x 1

print("====== Q =======")
print(Q)
print()

print("====== Sij =======")
Sij = Q @ K.T
print(Sij)
print()

print("====== mij_hat =======")
mij_hat = torch.max(Sij, dim=1).values[:, None]
print(mij_hat)
print()

print("====== pij_hat =======")
pij_hat = torch.exp(Sij - mij_hat)
print(pij_hat)
print()

print("====== lij_hat =======")
lij_hat = torch.sum(pij_hat, dim=1)[:, None]
print(lij_hat)
print()

print("====== mi_new =======")
mi_new = torch.max(torch.column_stack([mi, mij_hat]), dim=1).values[:, None]
print(mi_new)
print()

print("====== li_new =======")
li_new = torch.exp(mi - mi_new) * li + torch.exp(mij_hat - mi_new) * lij_hat
print(li_new)
print()

print("====== O =======")
O = (li * torch.exp(mi - mi_new) * O / li_new) + (torch.exp(mij_hat - mi_new) * pij_hat / li_new) @ V
print(O)
print()


====== Q =======
tensor([[0.1000, 0.2000, 0.3000, 0.4000],
        [0.5000, 0.6000, 0.7000, 0.8000],
        [0.9000, 1.0000, 1.1000, 1.2000],
        [1.3000, 1.4000, 1.5000, 1.6000]])

====== Sij =======
tensor([[0.3000, 0.7000, 1.1000, 1.5000],
        [0.7000, 1.7400, 2.7800, 3.8200],
        [1.1000, 2.7800, 4.4600, 6.1400],
        [1.5000, 3.8200, 6.1400, 8.4600]])

====== mij_hat =======
tensor([[1.5000],
        [3.8200],
        [6.1400],
        [8.4600]])

====== pij_hat =======
tensor([[3.0119e-01, 4.4933e-01, 6.7032e-01, 1.0000e+00],
        [4.4157e-02, 1.2493e-01, 3.5345e-01, 1.0000e+00],
        [6.4737e-03, 3.4735e-02, 1.8637e-01, 1.0000e+00],
        [9.4910e-04, 9.6577e-03, 9.8274e-02, 1.0000e+00]])

====== lij_hat =======
tensor([[2.4208],
        [1.5225],
        [1.2276],
        [1.1089]])

====== mi_new =======
tensor([[1.5000],
        [3.8200],
        [6.1400],
        [8.4600]])

====== li_new =======
tensor([[2.4208],
        [1.5225],
        [1.2276],
 

# 2-shot on K

In [12]:
seq_len = 4
d_head = 4

Q = (torch.arange(seq_len * d_head).reshape(seq_len, d_head) + 1.)  / 10
K = (torch.arange(seq_len * d_head).reshape(seq_len, d_head) + 1.)  / 10
V = (torch.arange(seq_len * d_head).reshape(seq_len, d_head) + 1.)  / 10
O = torch.zeros((seq_len, d_head))


m = torch.full((seq_len, 1), -torch.inf)
l = torch.zeros((seq_len, 1))

mi = m  # shape Br x 1
li = l  # shape Br x 1

# print("1st pass on K")
print("====== Q =======")
print(Q)
print()

print("====== Sij =======")
Sij = Q @ K[0:2, :].T
print(Sij)
print()

print("====== mij_hat =======")
mij_hat = torch.max(Sij, dim=1).values[:, None]
print(mij_hat)
print()

print("====== pij_hat =======")
pij_hat = torch.exp(Sij - mij_hat)
print(pij_hat)
print()

print("====== lij_hat =======")
lij_hat = torch.sum(pij_hat, dim=1)[:, None]
print(lij_hat)
print()

print("====== mi_new =======")
mi_new = torch.max(torch.column_stack([mi, mij_hat]), dim=1).values[:, None]
print(mi_new)
print()

print("====== li_new =======")
li_new = torch.exp(mi - mi_new) * li + torch.exp(mij_hat - mi_new) * lij_hat
print(li_new)
print()

print("====== O =======")
O = (li * torch.exp(mi - mi_new) * O / li_new) + (torch.exp(mij_hat - mi_new) * pij_hat / li_new) @ V[0:2, :]
print(O)
print()

mi = mi_new


====== Q =======
tensor([[0.1000, 0.2000, 0.3000, 0.4000],
        [0.5000, 0.6000, 0.7000, 0.8000],
        [0.9000, 1.0000, 1.1000, 1.2000],
        [1.3000, 1.4000, 1.5000, 1.6000]])

====== Sij =======
tensor([[0.3000, 0.7000],
        [0.7000, 1.7400],
        [1.1000, 2.7800],
        [1.5000, 3.8200]])

====== mij_hat =======
tensor([[0.7000],
        [1.7400],
        [2.7800],
        [3.8200]])

====== pij_hat =======
tensor([[0.6703, 1.0000],
        [0.3535, 1.0000],
        [0.1864, 1.0000],
        [0.0983, 1.0000]])

====== lij_hat =======
tensor([[1.6703],
        [1.3535],
        [1.1864],
        [1.0983]])

====== mi_new =======
tensor([[0.7000],
        [1.7400],
        [2.7800],
        [3.8200]])

====== li_new =======
tensor([[1.6703],
        [1.3535],
        [1.1864],
        [1.0983]])

====== O =======
tensor([[0.3395, 0.4395, 0.5395, 0.6395],
        [0.3955, 0.4955, 0.5955, 0.6955],
        [0.4372, 0.5372, 0.6372, 0.7372],
        [0.4642, 0.5642, 0.664

In [13]:
# print("2nd pass on K")
print("====== Q =======")
print(Q)
print()

print("====== Sij =======")
Sij = Q @ K[2:4, :].T
print(Sij)
print()

print("====== mij_hat =======")
mij_hat = torch.max(Sij, dim=1).values[:, None]
print(mij_hat)
print()

print("====== pij_hat =======")
pij_hat = torch.exp(Sij - mij_hat)
print(pij_hat)
print()

print("====== lij_hat =======")
lij_hat = torch.sum(pij_hat, dim=1)[:, None]
print(lij_hat)
print()

print("====== mi_new =======")
mi_new = torch.max(torch.column_stack([mi, mij_hat]), dim=1).values[:, None]
print(mi_new)
print()

print("====== li_new =======")
li_new = torch.exp(mi - mi_new) * li + torch.exp(mij_hat - mi_new) * lij_hat
print(li_new)
print()

print("====== O =======")
O = (li * torch.exp(mi - mi_new) * O / li_new) + (torch.exp(mij_hat - mi_new) * pij_hat / li_new) @ V[2:4, :]
print(O)
print()

====== Q =======
tensor([[0.1000, 0.2000, 0.3000, 0.4000],
        [0.5000, 0.6000, 0.7000, 0.8000],
        [0.9000, 1.0000, 1.1000, 1.2000],
        [1.3000, 1.4000, 1.5000, 1.6000]])

====== Sij =======
tensor([[1.1000, 1.5000],
        [2.7800, 3.8200],
        [4.4600, 6.1400],
        [6.1400, 8.4600]])

====== mij_hat =======
tensor([[1.5000],
        [3.8200],
        [6.1400],
        [8.4600]])

====== pij_hat =======
tensor([[0.6703, 1.0000],
        [0.3535, 1.0000],
        [0.1864, 1.0000],
        [0.0983, 1.0000]])

====== lij_hat =======
tensor([[1.6703],
        [1.3535],
        [1.1864],
        [1.0983]])

====== mi_new =======
tensor([[1.5000],
        [3.8200],
        [6.1400],
        [8.4600]])

====== li_new =======
tensor([[2.4208],
        [1.5225],
        [1.2276],
        [1.1089]])

====== O =======
tensor([[0.8915, 0.9915, 1.0915, 1.1915],
        [1.1067, 1.2067, 1.3067, 1.4067],
        [1.2103, 1.3103, 1.4103, 1.5103],
        [1.2566, 1.3566, 1.456

In [16]:
print(torch.exp(mi - mi_new) * li)
print(torch.exp(mij_hat - mi_new) * lij_hat)
print(li_new)

tensor([[0.7505],
        [0.1691],
        [0.0412],
        [0.0106]])
tensor([[1.6703],
        [1.3535],
        [1.1864],
        [1.0983]])
tensor([[2.4208],
        [1.5225],
        [1.2276],
        [1.1089]])


In [17]:
1.6703 + 0.7505

2.4208

In [ ]:
tensor([[0.8915, 0.9915, 1.0915, 1.1915],
        [1.1067, 1.2067, 1.3067, 1.4067],
        [1.2103, 1.3103, 1.4103, 1.5103],
        [1.2566, 1.3566, 1.4566, 1.5566]])

# Softmax

> https://arxiv.org/pdf/1805.02867.pdf

In [18]:
torch.manual_seed(0)

x = torch.arange(10, dtype=torch.float32)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [19]:
def naive_softmax(vec):
   return torch.exp(vec) / torch.sum(torch.exp(vec))

torch.allclose(torch.softmax(x.clone(), dim=0), naive_softmax(x.clone()))

True

In [20]:
def safe_softmax(vec):
    # Compute row max in 1st pass
    row_max = torch.max(vec)
    # Compute denominator in 2nd pass
    denominator = torch.sum(torch.exp(vec - row_max))
    return torch.exp(vec - row_max) / denominator


torch.allclose(torch.softmax(x.clone(), dim=0), safe_softmax(x.clone()))

True

In [39]:
#TODO: Cf goodnotes ipad "Flash attention"

def online_softmax(vec):
    N = len(vec)
    rowmax = -float("inf")
    denominator = 0
    # Compute the max and denominator in single pass
    for i in range(N):
        prev_rowmax = rowmax
        rowmax = max(prev_rowmax, vec[i])
        denominator = denominator * torch.exp(prev_rowmax - rowmax) + torch.exp(vec[i] - rowmax)
        print(f"prev_rowmax = {prev_rowmax} | rowmax = {rowmax} | denominator = {denominator}")

    print(torch.exp(vec - rowmax))
    print(denominator)
    return torch.exp(vec - rowmax) / denominator

torch.allclose(torch.softmax(x.clone(), dim=0), online_softmax(x.clone()))

prev_rowmax = -inf | rowmax = 0.0 | denominator = 1.0
prev_rowmax = 0.0 | rowmax = 1.0 | denominator = 1.3678793907165527
prev_rowmax = 1.0 | rowmax = 2.0 | denominator = 1.503214716911316
prev_rowmax = 2.0 | rowmax = 3.0 | denominator = 1.553001880645752
prev_rowmax = 3.0 | rowmax = 4.0 | denominator = 1.571317434310913
prev_rowmax = 4.0 | rowmax = 5.0 | denominator = 1.5780553817749023
prev_rowmax = 5.0 | rowmax = 6.0 | denominator = 1.5805342197418213
prev_rowmax = 6.0 | rowmax = 7.0 | denominator = 1.5814460515975952
prev_rowmax = 7.0 | rowmax = 8.0 | denominator = 1.5817815065383911
prev_rowmax = 8.0 | rowmax = 9.0 | denominator = 1.5819048881530762
tensor([1.2341e-04, 3.3546e-04, 9.1188e-04, 2.4788e-03, 6.7379e-03, 1.8316e-02,
        4.9787e-02, 1.3534e-01, 3.6788e-01, 1.0000e+00])
tensor(1.5819)


True

In [40]:
print(x)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [41]:
online_softmax(x.clone())

prev_rowmax = -inf | rowmax = 0.0 | denominator = 1.0
prev_rowmax = 0.0 | rowmax = 1.0 | denominator = 1.3678793907165527
prev_rowmax = 1.0 | rowmax = 2.0 | denominator = 1.503214716911316
prev_rowmax = 2.0 | rowmax = 3.0 | denominator = 1.553001880645752
prev_rowmax = 3.0 | rowmax = 4.0 | denominator = 1.571317434310913
prev_rowmax = 4.0 | rowmax = 5.0 | denominator = 1.5780553817749023
prev_rowmax = 5.0 | rowmax = 6.0 | denominator = 1.5805342197418213
prev_rowmax = 6.0 | rowmax = 7.0 | denominator = 1.5814460515975952
prev_rowmax = 7.0 | rowmax = 8.0 | denominator = 1.5817815065383911
prev_rowmax = 8.0 | rowmax = 9.0 | denominator = 1.5819048881530762
tensor([1.2341e-04, 3.3546e-04, 9.1188e-04, 2.4788e-03, 6.7379e-03, 1.8316e-02,
        4.9787e-02, 1.3534e-01, 3.6788e-01, 1.0000e+00])
tensor(1.5819)


tensor([7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
        3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01])

In [47]:
torch.exp(x - torch.max(x))

tensor([1.2341e-04, 3.3546e-04, 9.1188e-04, 2.4788e-03, 6.7379e-03, 1.8316e-02,
        4.9787e-02, 1.3534e-01, 3.6788e-01, 1.0000e+00])

In [48]:
torch.sum(torch.exp(x - torch.max(x)))

tensor(1.5819)

In [49]:
torch.exp(x - torch.max(x)) / torch.sum(torch.exp(x - torch.max(x)))

tensor([7.8013e-05, 2.1206e-04, 5.7645e-04, 1.5669e-03, 4.2594e-03, 1.1578e-02,
        3.1473e-02, 8.5552e-02, 2.3255e-01, 6.3215e-01])